grafana:
  adminPassword: "CHANGEME"     # change later
  
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.48.223.233.230.nip.io   # <= use your nip.io host

imageRenderer:
    enabled: true 

